#import "common.typ": *

#show: rockable-sheet.with(
  title: [`Rockable` command lines, build options and file layout],
)

= `rockable` --- running a simulation

#concept-block(body: [
  #align(center, command("rockable [conf-file] [options]"))

  The positional argument defaults to `conf0`. Everything happens in the
  *current folder*: the companion files are looked up there, and the dumps are
  written there.

  #kwtable(
    command("-j, --nbThreads <int>"), [Number of OpenMP threads (default `1`).
      The parallel strategy itself is the conf-file keyword
      #command("parallel_mode").],
    command("-v, --verbose <int>"), [Verbosity, from `0` to `6`: `off`,
      `critical`, `err`, `warn`, `info` (default), `debug`, `trace`.],
    command("-c, --clean"), [Delete `conf*`, `perf.txt`, `kineticEnergy.txt`,
      `staticBalance.txt` and `checkplots.txt` from the current folder, then
      exit. #note[There is no confirmation.]],
    command("-b, --banner"), [Print the banner --- version, git tag and the
      compilation options actually used --- then exit.],
    command("-n <new> -r <ref>"), [Non-regression check: after the run, compare
      two conf-files line by line from their `Particles` section onwards, and
      exit with an error if they differ.],
    command("-h, --help"), [The usual help, generated by `tclap`.],
    command("--version"), [The git tag Rockable was built from.],
  )

  ```sh
  rockable input.txt -j 8 -v 5
  ```
])

= The other executables

#concept-block(body: [
  #kwtable(
    command("see [conf-file]"), [The `freeglut` 3D viewer. `-t <file>` for a
      trajectory file, `-v <int>` for the verbosity of the core.],
    command("seer"), [*Dear My Seer*, the Dear ImGui viewer that replaces `see`.],
    command("conftovtk"), [Convert *every* `conf*` of the folder into VTK files
      for ParaView.],
    command("postpro <commandFile>"), [Run a post-processor over a range of
      dumps.],
    command("generator <commandFile>"), [Build shape files, input files and
      packings.],
    command("shapeSurvey <shapeFile>"), [Inspect and pre-compute a shape
      library.],
    command("sweepable [script]"), [Generate a tree of input files for a
      parameter sweep.],
    command("stl2shape -i <f.stl> -r <R>"), [Convert a *binary* STL into a
      shape.],
  )
])

= Building

#concept-block(body: [
  ```sh
  git clone https://github.com/richefeu/rockable.git
  cd rockable
  sh install_rockable.sh
  ```
  The build happens in #file("BUILD/") and the binaries land in
  #file("INSTALL/"). System packages that may be needed beforehand: `glfw3`,
  `opengl`, `freeglut`, and `libpng` (optional, for PNG screenshots).

  To change the options:
  ```sh
  cd BUILD
  ccmake .        # set the options, then c, e, g
  cmake ..
  make -j
  make install
  ```

  #note[Dependencies (`toofus`, `tclap`, `fmt`, ...) are fetched by CMake into
  #file("deps/").]
])

= CMake options

#concept-block(body: [
  #inline("Features (change the physics or the keywords)")
  All default to `OFF`.
  - #command("ROCKABLE_ENABLE_PERIODIC") ~Tri-periodic cell: the
    `usePeriodicCell`, `h`, `vh`, `ah`, `mh`, `dh`, ... keywords and the
    `PeriodicLoading` drivings. Without it, those keywords only print a warning.
  - #command("ROCKABLE_ENABLE_SOFT_PARTICLES") ~Homogeneous straining of the
    particles (`useSoftParticles`).
  - #command("ROCKABLE_ENABLE_BOUNDARY") ~The special boundary shapes (`Ball`,
    `Cylinder`). #note[Still incomplete in the source.]
  - #command("ROCKABLE_USE_FT_CORR") ~Objectivity correction of the tangential
    forces under large rotations.
  - #command("ROCKABLE_ENABLE_PROFILING") ~Time profiling of the main routines,
    reported into #file("perf.txt").

  #inline("What gets compiled")
  #kwtable(
    command("ROCKABLE_COMPILE_SEE"), [`see`.],
    command("ROCKABLE_COMPILE_SEER"), [`seer` (Dear My Seer).],
    command("ROCKABLE_COMPILE_CONF2VTK"), [`conftovtk`.],
    command("ROCKABLE_COMPILE_POSTPRO"), [`postpro`.],
    command("ROCKABLE_COMPILE_PREPRO"), [The pre-processing tools.],
    command("ROCKABLE_USE_TESTING"), [The non-regression tests.],
  )

  #note[`rockable -b` prints which of these were actually enabled --- the
  quickest way to explain a keyword that "does nothing".]
])

= Layout of the repository

#concept-block(body: [
  #kwtable(
    file("src/Core"), [`Rockable`, `Particle`, `Shape`, `Interaction`,
      `DrivingSystem`, `PeriodicCell`, ... the heart of the code.],
    file("src/Apps"), [`run.cpp` (the `rockable` binary), `see.cpp`,
      `postpro.cpp`, `conftovtk.cpp`, `DearMySeer/`, `DearMyShape/`.],
    file("src/ForceLaws"), [One file per interaction model.],
    file("src/BodyForces"), [One file per body force.],
    file("src/DataExtractors"), [One file per on-the-fly measurement.],
    file("src/PreproCommands"), [One file per pre-processing command.],
    file("src/PostProcessors"), [One file per post-processor.],
    file("src/ProcessingTools"), [Reusable analyses: clusters, broken
      sub-clusters, interaction groups, mass range, solid fraction probe.],
    file("src/Boundaries"), [Special boundaries #boundary-flag.],
    file("prepro"), [`generable` (the `generator`), `genesis`, `shapesurvey`,
      `sweepable`, `converters`, `confedit`.],
    file("examples"), [Example simulations. `helloworld` is the entry point;
      the rest is a sandbox.],
    file("test"), [Non-regression tests.],
    file("sphinxdoc"), [The Sphinx sources of the online documentation.],
    file("deps"), [Dependency sources fetched by CMake.],
  )

  #inline("Adding a force law, an extractor, a command...")
  Each of these families is registered through a *factory*: drop a new
  `.cpp`/`.hpp` pair in the right folder, register the name, and it becomes
  usable from the conf-file without touching the parser.
])

= Layout of a simulation folder

#concept-block(body: [
  ```txt
  mySimulation/
    input.txt              # the conf-file you write
    shapes.txt             # shape library (shapeFile)
    shapes.rmsh            # optional skin meshes, for see
    drivingSystem.txt      # optional driving / servo
    dataExtractors.txt     # optional measurements
    see.json               # optional view settings
    probe.txt              # optional measurement box
    -------- produced by the run --------
    conf0 conf1 conf2 ...  # the dumps
    extractedDataDoc.txt   # what the extractors write
    perf.txt
    kineticEnergy.txt
    staticBalance.txt
    checkplots.txt         # gnuplot checkplots.txt
  ```

  #inline("Restarting")
  Any dump is a valid input, so
  ```sh
  rockable conf27 -j 8
  ```
  resumes from configuration 27. The companion files are re-read from the
  folder, which is how a driving can be changed mid-course.

  #inline("Pointing at another folder")
  A conf-file whose first token is #command("redirection") is a one-line
  indirection: it holds a path and a conf-file name, and that file is loaded
  instead. It is what the tests use to share one sample between several cases.
])
